### ISSUE TITLE
Definir Navegación

### ISSUE THREAD

**Issue by MuseroChopiniano** [MuseroChopiniano/FerreteriaLPPA#1]

**Comment by FacundoTripelhorn** [comment]
Pensé en una navegación jerárquica que tenga la página principal en un primer nivel
En un segundo nivel: productos, quienes somos, contacto, inicar sesión o mi cuenta, mi carrito, buscar
En un tercer nivel: categorías de productos y opciones de la cuenta

**Comment by FacundoTripelhorn** [comment]
Un ejemplo sería el menu de navegación de esta página https://www.neo.com.ar/
Estaría bueno hacer algo parecido
